remote_theme : codeasashu/hcz-jekyll-blog

title: 64BitO2
description: My Personal Blog And Portfolio
author: 64BitO2
logo: /static/img/avatar.png
github: https://github.com/64BitO2
about: Reversing, Information Security and etc.

baseurl: "https://64bito2.github.io"
url: ""

allowsearch: true

disqus_shortname: 64bito2
google_analytics:

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]